# Generated by Django 5.1 on 2024-08-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_remove_product_description_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='UserCart',
        ),
    ]
