# Generated by Django 5.1 on 2024-08-09 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0008_doctorpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpermission',
            name='accepted_orders',
        ),
        migrations.AddField(
            model_name='doctorpermission',
            name='accepted_orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_orders', to='restapp.order'),
        ),
    ]
