# Generated by Django 5.1 on 2024-08-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0009_remove_doctorpermission_accepted_orders_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorPermission',
        ),
    ]
